### PR TITLE
antiblazes thing

### PR DESCRIPTION
**Pull request by AntiBlaze1**
did some stuff

### CODE REVIEW

**Comment by AntiBlaze1** [comment]
is ur internet rly that bad

**Comment by OranGot** [comment]
don't put the images in the same dir as your files instead put them into pictures/call the directory something. Also you should have used the general stylesheet instead of putting your own but I will in some time

**Comment by OranGot** [comment]
and yes it is

**Comment by AntiBlaze1** [comment]
ok ill fix images

**Comment by AntiBlaze1** [comment]
ok fixed

**Pull request merged**
